import { useEffect, useState, type ReactElement } from 'react';
import { Button, Divider, Select, Tag, Typography } from 'antd';
import { PauseOutlined, PlayCircleOutlined } from '@ant-design/icons';
import type { DevelopmentRunView, SkillFeature } from './project-development-types';

type Props = { run: DevelopmentRunView; features?: SkillFeature[]; installedFeatureIds?: string[]; onFeatureAdd?: (feature: SkillFeature) => void; onManageSkills?: () => void; onPause: () => void; onContinue: () => void };
const LABELS = { idle: '等待开始', running: '运行中', paused: '已暂停', completed: '已完成', error: '执行失败', stopped: '已停止' } as const;
const elapsed = (startedAt: number | null) => startedAt === null ? '00:00' : `${String(Math.floor((Date.now() - startedAt) / 60000)).padStart(2, '0')}:${String(Math.floor((Date.now() - startedAt) / 1000) % 60).padStart(2, '0')}`;

export function DevelopmentRunPanel({ run, features = [], installedFeatureIds = [], onFeatureAdd, onManageSkills, onPause, onContinue }: Props): ReactElement {
  const [clock, setClock] = useState(0); const [selectedFeatureId, setSelectedFeatureId] = useState<string>();
  useEffect(() => { if (run.status !== 'running') return undefined; const timer = window.setInterval(() => setClock((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [run.status]); void clock;
  useEffect(() => { if (selectedFeatureId && !features.some((feature) => feature.id === selectedFeatureId)) setSelectedFeatureId(undefined); }, [features, selectedFeatureId]);
  const selectedFeature = features.find((feature) => feature.id === selectedFeatureId);
  const featureOptions = features.map((feature) => ({ value: feature.id, label: <span className="feature-option"><span>{feature.name}</span>{installedFeatureIds.includes(feature.id) && <span aria-label="已添加">✓</span>}</span> }));
  return <aside className="development-run"><section className="feature-picker"><div className="feature-picker-title-row"><div className="feature-picker-title">功能库</div>{onManageSkills && <Button type="link" size="small" onClick={onManageSkills}>管理技能</Button>}</div><div className="feature-picker-row"><Select size="small" value={selectedFeatureId} allowClear placeholder="选择功能" options={featureOptions} onChange={setSelectedFeatureId} /><Button size="small" type="primary" disabled={!selectedFeature || installedFeatureIds.includes(selectedFeature.id)} onClick={() => { if (selectedFeature) onFeatureAdd?.(selectedFeature); }}>确认添加</Button></div></section><header className="run-head"><div><Typography.Text className="eyebrow">RUNTIME</Typography.Text><Typography.Title level={4}>运行状态</Typography.Title></div><Tag color={run.status === 'running' ? 'gold' : run.status === 'error' ? 'red' : 'blue'}>{LABELS[run.status]}</Tag></header><div className="run-summary"><div className="run-state"><Typography.Text>{LABELS[run.status]}</Typography.Text><Typography.Title level={3}>{elapsed(run.startedAt)}</Typography.Title></div><Typography.Text type="secondary">{run.currentAction}</Typography.Text><div className="run-counters"><span><strong>{run.commandCount}</strong> 命令</span><span><strong>{run.changedPaths.length}</strong> 文件变更</span></div></div><Divider /><div className="run-log-head"><span>运行日志</span><small>{run.logs.length.toString().padStart(2, '0')} EVENTS</small></div><ol className="run-log">{run.logs.map((log) => <li key={log.id}><span className="log-dot" /><span><strong>{log.label}</strong>{log.detail && <small>{log.detail}</small>}</span></li>)}</ol>{run.status === 'running' && <Button icon={<PauseOutlined />} onClick={onPause}>暂停开发</Button>}{run.status === 'paused' && <Button type="primary" icon={<PlayCircleOutlined />} onClick={onContinue}>继续开发</Button>}</aside>;
}
