import { Button, Dropdown, Empty, Popconfirm, Tooltip, Typography } from 'antd';
import { DeleteOutlined, FolderAddOutlined, FolderOutlined, PlusOutlined } from '@ant-design/icons';
import type { ReactElement } from 'react';
import type { Project } from '../project-statistics/project-statistics-types';
import type { DevelopmentSession } from './project-development-types';

type Props = { sessions: DevelopmentSession[]; projects: Project[]; workspaceIds: string[]; selectedWorkspaceId: string; activeId: string; onWorkspaceSelect: (workspaceId: string) => void; onWorkspaceAdd: (workspaceId: string) => void; onSelect: (id: string) => void; onCreate: (workspaceId?: string) => void; onDelete: (session: DevelopmentSession) => void; creating: boolean };

// 中文注释：左栏按工作区分组显示会话，工作区实际复用项目目录，避免引入新的持久化模型。
export function DevelopmentSessionList({ sessions, projects, workspaceIds, selectedWorkspaceId, activeId, onWorkspaceSelect, onWorkspaceAdd, onSelect, onCreate, onDelete, creating }: Props): ReactElement {
  const workspaces = workspaceIds.map((id) => projects.find((project) => project.id === id)).filter((project): project is Project => project !== undefined);
  const workspaceMenuItems = projects.length > 0 ? projects.map((project) => ({ key: project.id, icon: <FolderOutlined />, label: project.name })) : [{ key: 'empty', label: '暂无可用项目', disabled: true }];
  return <aside className="development-sessions reference-sidebar"><div className="development-sidebar-toolbar"><Dropdown trigger={['click']} menu={{ items: workspaceMenuItems, onClick: ({ key }) => onWorkspaceAdd(key) }}><Button icon={<FolderAddOutlined />} disabled={creating}>新增工作区</Button></Dropdown><Button type="primary" icon={<PlusOutlined />} onClick={() => onCreate()} disabled={!selectedWorkspaceId || creating}>新建会话</Button></div><div className="workspace-list">{workspaces.map((workspace) => { const workspaceSessions = sessions.filter((session) => session.projectId === workspace.id); const selected = workspace.id === selectedWorkspaceId; return <section className={selected ? 'workspace-group selected' : 'workspace-group'} key={workspace.id}><div className="workspace-item"><Button type="text" className="workspace-select" onClick={() => onWorkspaceSelect(workspace.id)}><FolderOutlined /><span className="workspace-name">{workspace.name}</span></Button><Tooltip title="在此工作区新建会话"><Button type="text" className="workspace-create" icon={<PlusOutlined />} aria-label={`在工作区 ${workspace.name} 新建会话`} onClick={() => onCreate(workspace.id)} disabled={creating} /></Tooltip></div><div className="workspace-session-list">{workspaceSessions.map((session) => <div key={session.id} className={session.id === activeId ? 'session-item active' : 'session-item'}><Button type="text" className="session-select" onClick={() => onSelect(session.id)}><span className="session-copy"><strong className="session-name">{session.title}</strong></span></Button><Popconfirm title="删除会话" description={`确定删除会话「${session.title}」吗？`} okText="删除" cancelText="取消" okButtonProps={{ danger: true }} onConfirm={() => onDelete(session)}><Button type="text" danger className="session-delete" icon={<DeleteOutlined />} aria-label={`删除会话 ${session.title}`} /></Popconfirm></div>)}</div>{workspaceSessions.length === 0 && <Typography.Text type="secondary" className="workspace-empty">暂无会话，点击右侧 + 新建</Typography.Text>}</section>; })}{workspaces.length === 0 && <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="点击“新增工作区”开始" />}</div></aside>;
}
