import { useEffect, useState, type ReactElement } from 'react';
import { Alert, Empty, Modal } from 'antd';
import { fetchProjectList } from '../project-statistics/project-statistics-api';
import type { Project } from '../project-statistics/project-statistics-types';
import { DevelopmentChatPanel } from './development-chat-panel';
import { DevelopmentRunPanel } from './development-run-panel';
import { DevelopmentSessionList } from './development-session-list';
import { continueDevelopment, createSession, deleteSession, deleteSkillFeature, deleteWorkspace, extractSkill, getSession, getSkillFeature, importSkill, listSessions, listSkillFeatures, openProjectPath, pauseDevelopment, registerProjectDirectory, selectWorkspaceDirectory, sendMessage, startDevelopment, subscribeDevelopmentEvents } from './project-development-api';
import type { DevelopmentEvent, DevelopmentEventEnvelope, DevelopmentMessage, DevelopmentMode, DevelopmentRunView, DevelopmentSession, DevelopmentSessionDetail, FeatureExtractionCandidate, SkillFeature } from './project-development-types';
import { SkillManagementModal } from './skill-management-modal';
import { SkillExtractionConfirmModal } from './skill-extraction-confirm-modal';
import './project-development.css';

const EMPTY_RUN: DevelopmentRunView = { status: 'idle', startedAt: null, commandCount: 0, changedPaths: [], currentAction: '等待 AI 任务', logs: [] };
const eventLog = (event: DevelopmentEvent) => event.type === 'command-started' ? { label: '开始执行命令', detail: event.command } : event.type === 'file-change' ? { label: '文件发生变更', detail: event.paths.join('、') } : event.type === 'run-error' ? { label: '执行错误', detail: event.message } : { label: event.type === 'turn-completed' ? '本次任务完成' : '收到运行事件' };
const asError = (reason: unknown) => reason instanceof Error ? reason.message : String(reason);
const SESSION_ORDER_KEY = 'project-development.session-order.v1';
type SessionOrderMap = Record<string, string[]>;
const readSessionOrder = (): SessionOrderMap => { try { const value = JSON.parse(localStorage.getItem(SESSION_ORDER_KEY) ?? '{}'); return value !== null && typeof value === 'object' ? value as SessionOrderMap : {}; } catch { return {}; } };
const saveSessionOrder = (value: SessionOrderMap) => { try { localStorage.setItem(SESSION_ORDER_KEY, JSON.stringify(value)); } catch { /* 本地存储不可用时仍保留当前页面排序 */ } };
const orderSessions = (items: DevelopmentSession[], order: SessionOrderMap): DevelopmentSession[] => items.slice().sort((left, right) => { if (left.projectId !== right.projectId) return 0; const ids = order[left.projectId] ?? []; const leftIndex = ids.indexOf(left.id); const rightIndex = ids.indexOf(right.id); if (leftIndex < 0 && rightIndex < 0) return 0; if (leftIndex < 0) return 1; if (rightIndex < 0) return -1; return leftIndex - rightIndex; });
const mergeSessionOrder = (items: DevelopmentSession[], current: SessionOrderMap): SessionOrderMap => { const next = { ...current }; for (const projectId of new Set(items.map((item) => item.projectId))) { const ids = items.filter((item) => item.projectId === projectId).map((item) => item.id); const saved = current[projectId] ?? []; next[projectId] = [...saved.filter((id) => ids.includes(id)), ...ids.filter((id) => !saved.includes(id))]; } return next; };

export function ProjectDevelopmentPage(): ReactElement {
  const [sessions, setSessions] = useState<DevelopmentSession[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [selectedWorkspaceId, setSelectedWorkspaceId] = useState(''); const [activeSession, setActiveSession] = useState<DevelopmentSessionDetail | null>(null); const [runBySession, setRunBySession] = useState<Record<string, DevelopmentRunView>>({}); const [features, setFeatures] = useState<SkillFeature[]>([]); const [installedFeatureIds, setInstalledFeatureIds] = useState<string[]>([]); const [selectedFeatureId, setSelectedFeatureId] = useState<string>(); const [skillManagerOpen, setSkillManagerOpen] = useState(false); const [extractionCandidate, setExtractionCandidate] = useState<FeatureExtractionCandidate | null>(null); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [sessionOrder, setSessionOrder] = useState<SessionOrderMap>(() => readSessionOrder());
  const activeRun = activeSession ? (runBySession[activeSession.id] ?? EMPTY_RUN) : EMPTY_RUN;
  const selectedSkillId = features.find((feature) => feature.id === selectedFeatureId)?.skillId;
  const refreshSkills = () => void listSkillFeatures().then(setFeatures).catch((reason: unknown) => setError(asError(reason)));
  useEffect(() => { void Promise.all([listSessions(), fetchProjectList({ status: 'all' }), listSkillFeatures()]).then(([items, allProjects, availableFeatures]) => { const nextOrder = mergeSessionOrder(items, readSessionOrder()); setSessionOrder(nextOrder); saveSessionOrder(nextOrder); setSessions(orderSessions(items, nextOrder)); setProjects(allProjects); setFeatures(availableFeatures); const firstWorkspaceId = items[0]?.projectId ?? allProjects[0]?.id; if (firstWorkspaceId === undefined) return; setSelectedWorkspaceId(firstWorkspaceId); const firstSession = items.find((item) => item.projectId === firstWorkspaceId); if (firstSession !== undefined) void getSession(firstSession.id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason))); }).catch((reason: unknown) => setError(asError(reason))); }, []);
  useEffect(() => subscribeDevelopmentEvents((envelope: DevelopmentEventEnvelope) => { const event = envelope.event; if (event.type === 'feature-extraction-ready') setExtractionCandidate(event.candidate); if (event.type === 'feature-extraction-failed') setError(event.message); setRunBySession((current) => { const previous = current[envelope.sessionId] ?? EMPTY_RUN; const next = { ...previous, logs: [...previous.logs, { id: `${Date.now()}-${previous.logs.length}`, ...eventLog(event) }].slice(-100) }; if (event.type === 'turn-started' || event.type === 'command-started') next.status = 'running'; if (event.type === 'command-started') { next.commandCount += 1; next.currentAction = event.command; } if (event.type === 'file-change') next.changedPaths = [...new Set([...next.changedPaths, ...event.paths])]; if (event.type === 'run-error') { next.status = 'error'; next.currentAction = event.message; } if (event.type === 'turn-completed' || (event.type === 'process-exited' && !event.stopped)) { next.status = 'completed'; next.currentAction = '本次任务完成'; } if (event.type === 'process-exited' && event.stopped) { next.status = event.paused ? 'paused' : 'stopped'; next.currentAction = event.paused ? '开发已暂停' : '用户已停止任务'; } return { ...current, [envelope.sessionId]: next }; }); if (activeSession?.id === envelope.sessionId) void getSession(envelope.sessionId).then(setActiveSession).catch(() => undefined); }), [activeSession?.id]);
  const selectWorkspace = (id: string) => { setSelectedWorkspaceId(id); setActiveSession(null); const first = sessions.find((item) => item.projectId === id); if (first) void getSession(first.id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason))); };
  const addWorkspace = () => { setCreating(true); void selectWorkspaceDirectory().then((path) => path === null ? null : registerProjectDirectory(path)).then((project) => { if (project === null) return; setProjects((current) => [project, ...current.filter((item) => item.id !== project.id)]); setSelectedWorkspaceId(project.id); setActiveSession(null); }).catch((reason: unknown) => setError(asError(reason))).finally(() => setCreating(false)); };
  const selectSession = (id: string) => void getSession(id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason)));
  const removeSession = (session: DevelopmentSession) => { void deleteSession(session.id).then(() => listSessions()).then((items) => { const nextOrder = mergeSessionOrder(items, sessionOrder); setSessionOrder(nextOrder); saveSessionOrder(nextOrder); setSessions(orderSessions(items, nextOrder)); if (activeSession?.id === session.id) setActiveSession(null); }).catch((reason: unknown) => setError(asError(reason))); };
  const reorder = (workspaceId: string, sessionIds: string[]) => { const nextOrder = { ...sessionOrder, [workspaceId]: sessionIds }; setSessionOrder(nextOrder); saveSessionOrder(nextOrder); setSessions((items) => orderSessions(items, nextOrder)); };
  const create = (workspaceId = selectedWorkspaceId) => { if (!workspaceId) return; setSelectedWorkspaceId(workspaceId); setCreating(true); void createSession(workspaceId).then((item) => { setActiveSession(item); return listSessions(); }).then((items) => { const nextOrder = mergeSessionOrder(items, sessionOrder); setSessionOrder(nextOrder); saveSessionOrder(nextOrder); setSessions(orderSessions(items, nextOrder)); }).catch((reason: unknown) => setError(asError(reason))).finally(() => setCreating(false)); };
  const removeWorkspace = (workspace: Project) => { Modal.confirm({ title: '删除工作区', content: `仅移除「${workspace.name}」的登记和开发会话，本地文件夹与代码不会删除。确定继续吗？`, okText: '删除登记', cancelText: '取消', okButtonProps: { danger: true }, onOk: async () => { try { await deleteWorkspace(workspace.id); const [items, allProjects] = await Promise.all([listSessions(), fetchProjectList({ status: 'all' })]); const nextOrder = mergeSessionOrder(items, sessionOrder); delete nextOrder[workspace.id]; setSessionOrder(nextOrder); saveSessionOrder(nextOrder); setSessions(orderSessions(items, nextOrder)); setProjects(allProjects); const nextWorkspaceId = allProjects.find((item) => item.id !== workspace.id)?.id ?? ''; setSelectedWorkspaceId(nextWorkspaceId); setActiveSession(null); const nextSession = items.find((item) => item.projectId === nextWorkspaceId); if (nextSession) void getSession(nextSession.id).then(setActiveSession).catch(() => undefined); } catch (reason) { setError(asError(reason)); throw reason; } } }); };
  const run = (action: () => Promise<void>, message: string) => { if (!activeSession) return; setRunBySession((current) => ({ ...current, [activeSession.id]: { ...EMPTY_RUN, status: 'running', startedAt: Date.now(), currentAction: message, logs: [{ id: `${Date.now()}`, label: message }] } })); void action().catch((reason: unknown) => setError(asError(reason))); };
  const send = (message: string, mode: DevelopmentMode = 'discussion') => { if (!activeSession) return; const sessionId = activeSession.id; const optimistic: DevelopmentMessage = { id: `pending-${Date.now()}`, sessionId, role: 'user', content: message, createdAt: new Date().toISOString() }; setActiveSession((current) => current?.id === sessionId ? { ...current, messages: [...current.messages, optimistic] } : current); run(() => sendMessage(sessionId, message, mode, selectedSkillId), mode === 'feature-extraction' ? '正在分析可封装功能' : '正在启动 Codex'); };
  const addFeature = (feature: SkillFeature) => { const prompt = `请在当前项目中添加功能：${feature.name}。${feature.description}`; if (!activeSession) { if (!selectedWorkspaceId) return; setCreating(true); void createSession(selectedWorkspaceId).then((item) => { setActiveSession(item); setInstalledFeatureIds((current) => [...current, feature.id]); setSelectedFeatureId(feature.id); return sendMessage(item.id, prompt, 'development', feature.skillId); }).catch((reason: unknown) => setError(asError(reason))).finally(() => setCreating(false)); return; } setInstalledFeatureIds((current) => current.includes(feature.id) ? current : [...current, feature.id]); setSelectedFeatureId(feature.id); send(prompt, 'development'); };
  return <div className="development-page">{error && <Alert closable message={error} type="error" onClose={() => setError('')} />}<div className="development-workbench"><DevelopmentSessionList sessions={sessions} projects={projects} selectedWorkspaceId={selectedWorkspaceId} activeId={activeSession?.id ?? ''} onWorkspaceSelect={selectWorkspace} onWorkspaceAdd={addWorkspace} onWorkspaceOpen={(workspace) => { void openProjectPath(workspace.id).catch((reason: unknown) => setError(asError(reason))); }} onWorkspaceDelete={removeWorkspace} onSelect={selectSession} onCreate={create} onDelete={removeSession} onReorder={reorder} creating={creating} /><div className="development-center">{activeSession ? <DevelopmentChatPanel session={activeSession} runStatus={activeRun.status} error={error} onSend={send} onStart={() => run(() => startDevelopment(activeSession.id, selectedSkillId), '正在启动 Codex')} /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={selectedWorkspaceId ? '点击工作区中的 + 新建会话' : '点击“新增工作区”开始'} />}</div><DevelopmentRunPanel run={activeRun} features={features} installedFeatureIds={installedFeatureIds} onFeatureAdd={addFeature} onManageSkills={() => setSkillManagerOpen(true)} onPause={() => { if (activeSession) void pauseDevelopment(activeSession.id).catch((reason: unknown) => setError(asError(reason))); }} onContinue={() => { if (activeSession) run(() => continueDevelopment(activeSession.id), '正在继续开发'); }} /></div><SkillManagementModal open={skillManagerOpen} features={features} onClose={() => setSkillManagerOpen(false)} onImport={() => { void window.desktopApi.selectDirectory().then((path) => path ? importSkill(path) : null).then(() => refreshSkills()); }} onDelete={async (id) => { await deleteSkillFeature(id); setInstalledFeatureIds((current) => current.filter((featureId) => featureId !== id)); if (selectedFeatureId === id) setSelectedFeatureId(undefined); refreshSkills(); }} getFeature={getSkillFeature} />{extractionCandidate !== null && <SkillExtractionConfirmModal candidate={extractionCandidate} onCancel={() => setExtractionCandidate(null)} onConfirm={async (candidate) => { try { await extractSkill(candidate); setExtractionCandidate(null); refreshSkills(); } catch (reason) { setError(asError(reason)); } }} />}</div>;
}
