import { useEffect, useState, type ReactElement } from 'react';
import { Alert, Empty } from 'antd';
import { fetchProjectList } from '../project-statistics/project-statistics-api';
import type { Project } from '../project-statistics/project-statistics-types';
import { DevelopmentChatPanel } from './development-chat-panel';
import { DevelopmentRunPanel } from './development-run-panel';
import { DevelopmentSessionList } from './development-session-list';
import { createSession, deleteSession, getSession, listSessions, sendMessage, startDevelopment, stopDevelopment, subscribeDevelopmentEvents } from './project-development-api';
import type { DevelopmentEvent, DevelopmentEventEnvelope, DevelopmentRunView, DevelopmentSession, DevelopmentSessionDetail } from './project-development-types';
import './project-development.css';

const EMPTY_RUN: DevelopmentRunView = { status: 'idle', startedAt: null, commandCount: 0, changedPaths: [], currentAction: '等待 AI 任务', logs: [] };
const eventLog = (event: DevelopmentEvent) => event.type === 'command-started' ? { label: '开始执行命令', detail: event.command } : event.type === 'file-change' ? { label: '文件发生变更', detail: event.paths.join('、') } : event.type === 'run-error' ? { label: '执行错误', detail: event.message } : { label: event.type === 'turn-completed' ? '本次任务完成' : '收到运行事件' };
const asError = (reason: unknown) => reason instanceof Error ? reason.message : String(reason);

// 中文注释：项目开发页默认进入 AI 工作台，只有选择项目后才允许创建会话和发送消息。
export function ProjectDevelopmentPage(): ReactElement {
  const [sessions, setSessions] = useState<DevelopmentSession[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [selectedProjectId, setSelectedProjectId] = useState(''); const [activeSession, setActiveSession] = useState<DevelopmentSessionDetail | null>(null); const [runBySession, setRunBySession] = useState<Record<string, DevelopmentRunView>>({}); const [error, setError] = useState(''); const [creating, setCreating] = useState(false);
  const activeRun = activeSession ? (runBySession[activeSession.id] ?? EMPTY_RUN) : EMPTY_RUN;
  useEffect(() => { void Promise.all([listSessions(), fetchProjectList({ status: 'all' })]).then(([items, allProjects]) => { setSessions(items); setProjects(allProjects); const firstProject = allProjects[0]; if (firstProject === undefined) return; setSelectedProjectId(firstProject.id); const firstSession = items.find((item) => item.projectId === firstProject.id); if (firstSession !== undefined) void getSession(firstSession.id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason))); }).catch((reason: unknown) => setError(asError(reason))); }, []);
  useEffect(() => subscribeDevelopmentEvents((envelope: DevelopmentEventEnvelope) => { setRunBySession((current) => { const previous = current[envelope.sessionId] ?? EMPTY_RUN; const event = envelope.event; const next = { ...previous, logs: [...previous.logs, { id: `${Date.now()}-${previous.logs.length}`, ...eventLog(event) }].slice(-100) }; if (event.type === 'turn-started' || event.type === 'command-started') next.status = 'running'; if (event.type === 'command-started') { next.commandCount += 1; next.currentAction = event.command; } if (event.type === 'file-change') next.changedPaths = [...new Set([...next.changedPaths, ...event.paths])]; if (event.type === 'run-error') { next.status = 'error'; next.currentAction = event.message; } if (event.type === 'turn-completed' || (event.type === 'process-exited' && !event.stopped)) { next.status = 'completed'; next.currentAction = '本次任务完成'; } if (event.type === 'process-exited' && event.stopped) { next.status = 'stopped'; next.currentAction = '用户已停止任务'; } return { ...current, [envelope.sessionId]: next }; }); if (activeSession?.id === envelope.sessionId) void getSession(envelope.sessionId).then(setActiveSession).catch(() => undefined); }), [activeSession?.id]);
  const selectProject = (id: string) => { setSelectedProjectId(id); setActiveSession(null); const first = sessions.find((item) => item.projectId === id); if (first) void getSession(first.id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason))); };
  const selectSession = (id: string) => void getSession(id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason)));
  const removeSession = (session: DevelopmentSession) => { void deleteSession(session.id).then(() => listSessions()).then((items) => { setSessions(items); if (activeSession?.id === session.id) setActiveSession(null); }).catch((reason: unknown) => setError(asError(reason))); };
  const create = () => { if (!selectedProjectId) return; setCreating(true); void createSession(selectedProjectId).then((item) => { setActiveSession(item); return listSessions(); }).then(setSessions).catch((reason: unknown) => setError(asError(reason))).finally(() => setCreating(false)); };
  const run = (action: () => Promise<void>, message: string) => { if (!activeSession) return; setRunBySession((current) => ({ ...current, [activeSession.id]: { ...EMPTY_RUN, status: 'running', startedAt: Date.now(), currentAction: message, logs: [{ id: `${Date.now()}`, label: message }] } })); void action().catch((reason: unknown) => setError(asError(reason))); };
  return <div className="development-page">{error && <Alert closable message={error} type="error" onClose={() => setError('')} />}<div className="development-workbench"><DevelopmentSessionList sessions={sessions.filter((item) => item.projectId === selectedProjectId)} projects={projects} selectedProjectId={selectedProjectId} activeId={activeSession?.id ?? ''} onProjectSelect={selectProject} onSelect={selectSession} onCreate={create} onDelete={removeSession} creating={creating} /><div className="development-center">{activeSession ? <DevelopmentChatPanel session={activeSession} runStatus={activeRun.status} error={error} onSend={(message) => run(() => sendMessage(activeSession.id, message), '正在启动 Codex')} onStart={() => run(() => startDevelopment(activeSession.id), '正在启动 Codex')} /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={selectedProjectId ? '点击左侧 + 创建会话' : '请先选择项目后开始'} />}</div><DevelopmentRunPanel run={activeRun} onStop={() => { if (activeSession) void stopDevelopment(activeSession.id); }} /></div></div>;
}
