import { useEffect, useState, type ReactElement } from 'react';
import { Alert, Empty } from 'antd';
import { fetchProjectList } from '../project-statistics/project-statistics-api';
import type { Project } from '../project-statistics/project-statistics-types';
import { DevelopmentChatPanel } from './development-chat-panel';
import { DevelopmentRunPanel } from './development-run-panel';
import { DevelopmentSessionList } from './development-session-list';
import { continueDevelopment, createSession, deleteSession, deleteSkillFeature, getSession, getSkillFeature, importSkill, listSessions, listSkillFeatures, pauseDevelopment, sendMessage, startDevelopment, subscribeDevelopmentEvents } from './project-development-api';
import type { DevelopmentEvent, DevelopmentEventEnvelope, DevelopmentMessage, DevelopmentRunView, DevelopmentSession, DevelopmentSessionDetail, SkillFeature } from './project-development-types';
import { SkillManagementModal } from './skill-management-modal';
import './project-development.css';

const EMPTY_RUN: DevelopmentRunView = { status: 'idle', startedAt: null, commandCount: 0, changedPaths: [], currentAction: '等待 AI 任务', logs: [] };
const eventLog = (event: DevelopmentEvent) => event.type === 'command-started' ? { label: '开始执行命令', detail: event.command } : event.type === 'file-change' ? { label: '文件发生变更', detail: event.paths.join('、') } : event.type === 'run-error' ? { label: '执行错误', detail: event.message } : { label: event.type === 'turn-completed' ? '本次任务完成' : '收到运行事件' };
const asError = (reason: unknown) => reason instanceof Error ? reason.message : String(reason);

export function ProjectDevelopmentPage(): ReactElement {
  const [sessions, setSessions] = useState<DevelopmentSession[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [workspaceIds, setWorkspaceIds] = useState<string[]>([]); const [selectedWorkspaceId, setSelectedWorkspaceId] = useState(''); const [activeSession, setActiveSession] = useState<DevelopmentSessionDetail | null>(null); const [runBySession, setRunBySession] = useState<Record<string, DevelopmentRunView>>({}); const [features, setFeatures] = useState<SkillFeature[]>([]); const [installedFeatureIds, setInstalledFeatureIds] = useState<string[]>([]); const [selectedFeatureId, setSelectedFeatureId] = useState<string>(); const [skillManagerOpen, setSkillManagerOpen] = useState(false); const [error, setError] = useState(''); const [creating, setCreating] = useState(false);
  const activeRun = activeSession ? (runBySession[activeSession.id] ?? EMPTY_RUN) : EMPTY_RUN;
  const selectedSkillId = features.find((feature) => feature.id === selectedFeatureId)?.skillId;
  const refreshSkills = () => void listSkillFeatures().then(setFeatures).catch((reason: unknown) => setError(asError(reason)));
  useEffect(() => { void Promise.all([listSessions(), fetchProjectList({ status: 'all' }), listSkillFeatures()]).then(([items, allProjects, availableFeatures]) => { setSessions(items); setProjects(allProjects); setFeatures(availableFeatures); const ids = [...new Set(items.map((item) => item.projectId))]; setWorkspaceIds(ids); const firstWorkspaceId = ids[0]; if (firstWorkspaceId === undefined) return; setSelectedWorkspaceId(firstWorkspaceId); const firstSession = items.find((item) => item.projectId === firstWorkspaceId); if (firstSession !== undefined) void getSession(firstSession.id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason))); }).catch((reason: unknown) => setError(asError(reason))); }, []);
  useEffect(() => subscribeDevelopmentEvents((envelope: DevelopmentEventEnvelope) => { setRunBySession((current) => { const previous = current[envelope.sessionId] ?? EMPTY_RUN; const event = envelope.event; const next = { ...previous, logs: [...previous.logs, { id: `${Date.now()}-${previous.logs.length}`, ...eventLog(event) }].slice(-100) }; if (event.type === 'turn-started' || event.type === 'command-started') next.status = 'running'; if (event.type === 'command-started') { next.commandCount += 1; next.currentAction = event.command; } if (event.type === 'file-change') next.changedPaths = [...new Set([...next.changedPaths, ...event.paths])]; if (event.type === 'run-error') { next.status = 'error'; next.currentAction = event.message; } if (event.type === 'turn-completed' || (event.type === 'process-exited' && !event.stopped)) { next.status = 'completed'; next.currentAction = '本次任务完成'; } if (event.type === 'process-exited' && event.stopped) { next.status = event.paused ? 'paused' : 'stopped'; next.currentAction = event.paused ? '开发已暂停' : '用户已停止任务'; } return { ...current, [envelope.sessionId]: next }; }); if (activeSession?.id === envelope.sessionId) void getSession(envelope.sessionId).then(setActiveSession).catch(() => undefined); }), [activeSession?.id]);
  const selectWorkspace = (id: string) => { setSelectedWorkspaceId(id); setActiveSession(null); const first = sessions.find((item) => item.projectId === id); if (first) void getSession(first.id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason))); };
  const addWorkspace = (id: string) => { setWorkspaceIds((current) => current.includes(id) ? current : [...current, id]); selectWorkspace(id); };
  const selectSession = (id: string) => void getSession(id).then(setActiveSession).catch((reason: unknown) => setError(asError(reason)));
  const removeSession = (session: DevelopmentSession) => { void deleteSession(session.id).then(() => listSessions()).then((items) => { setSessions(items); if (activeSession?.id === session.id) setActiveSession(null); }).catch((reason: unknown) => setError(asError(reason))); };
  const create = (workspaceId = selectedWorkspaceId) => { if (!workspaceId) return; setSelectedWorkspaceId(workspaceId); setWorkspaceIds((current) => current.includes(workspaceId) ? current : [...current, workspaceId]); setCreating(true); void createSession(workspaceId).then((item) => { setActiveSession(item); return listSessions(); }).then(setSessions).catch((reason: unknown) => setError(asError(reason))).finally(() => setCreating(false)); };
  const run = (action: () => Promise<void>, message: string) => { if (!activeSession) return; setRunBySession((current) => ({ ...current, [activeSession.id]: { ...EMPTY_RUN, status: 'running', startedAt: Date.now(), currentAction: message, logs: [{ id: `${Date.now()}`, label: message }] } })); void action().catch((reason: unknown) => setError(asError(reason))); };
  const send = (message: string, mode: 'discussion' | 'development' = 'discussion') => { if (!activeSession) return; const sessionId = activeSession.id; const optimistic: DevelopmentMessage = { id: `pending-${Date.now()}`, sessionId, role: 'user', content: message, createdAt: new Date().toISOString() }; setActiveSession((current) => current?.id === sessionId ? { ...current, messages: [...current.messages, optimistic] } : current); run(() => sendMessage(sessionId, message, mode, selectedSkillId), '正在启动 Codex'); };
  const addFeature = (feature: SkillFeature) => { const prompt = `请在当前项目中添加功能：${feature.name}。${feature.description}`; if (!activeSession) { if (!selectedWorkspaceId) return; setCreating(true); void createSession(selectedWorkspaceId).then((item) => { setActiveSession(item); setInstalledFeatureIds((current) => [...current, feature.id]); setSelectedFeatureId(feature.id); return sendMessage(item.id, prompt, 'development', feature.skillId); }).catch((reason: unknown) => setError(asError(reason))).finally(() => setCreating(false)); return; } setInstalledFeatureIds((current) => current.includes(feature.id) ? current : [...current, feature.id]); setSelectedFeatureId(feature.id); send(prompt, 'development'); };
  return <div className="development-page">{error && <Alert closable message={error} type="error" onClose={() => setError('')} />}<div className="development-workbench"><DevelopmentSessionList sessions={sessions} projects={projects} workspaceIds={workspaceIds} selectedWorkspaceId={selectedWorkspaceId} activeId={activeSession?.id ?? ''} onWorkspaceSelect={selectWorkspace} onWorkspaceAdd={addWorkspace} onSelect={selectSession} onCreate={create} onDelete={removeSession} creating={creating} /><div className="development-center">{activeSession ? <DevelopmentChatPanel session={activeSession} runStatus={activeRun.status} error={error} onSend={send} onStart={() => run(() => startDevelopment(activeSession.id, selectedSkillId), '正在启动 Codex')} /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={selectedWorkspaceId ? '点击工作区中的 + 新建会话' : '点击“新增工作区”开始'} />}</div><DevelopmentRunPanel run={activeRun} features={features} installedFeatureIds={installedFeatureIds} onFeatureAdd={addFeature} onManageSkills={() => setSkillManagerOpen(true)} onPause={() => { if (activeSession) void pauseDevelopment(activeSession.id).catch((reason: unknown) => setError(asError(reason))); }} onContinue={() => { if (activeSession) run(() => continueDevelopment(activeSession.id), '正在继续开发'); }} /></div><SkillManagementModal open={skillManagerOpen} features={features} onClose={() => setSkillManagerOpen(false)} onImport={() => { void window.desktopApi.selectDirectory().then((path) => path ? importSkill(path) : null).then(() => refreshSkills()); }} onDelete={async (id) => { await deleteSkillFeature(id); setInstalledFeatureIds((current) => current.filter((featureId) => featureId !== id)); if (selectedFeatureId === id) setSelectedFeatureId(undefined); refreshSkills(); }} getFeature={getSkillFeature} /></div>;
}
