import type { ReactElement } from 'react';
import { Button, Empty, Input, Select, Spin, Typography } from 'antd';
import { PROJECT_FILTER_LABELS, type Project, type ProjectStatus, type ProjectStatusFilter } from '../project-statistics/project-statistics-types';
import { ProjectRow } from './project-row';

type LoadState = 'loading' | 'ready' | 'error';
interface ProjectListProps { loadState: LoadState; projects: Project[]; keyword: string; status: ProjectStatusFilter; busyProjectId: string | null; onKeywordChange: (keyword: string) => void; onStatusChange: (status: ProjectStatusFilter) => void; onClearFilters: () => void; onRetry: () => void; onStatusChangeForProject: (project: Project, next: ProjectStatus) => void; onRenameProject: (project: Project, newName: string) => Promise<void>; onArchiveProject: (project: Project) => void; onOpenPath: (project: Project) => void; onDevelop: (project: Project) => void; onImportTemplate: () => void; onCreateProject: () => void; }

// 中文注释：列表组件负责筛选和空状态，单行操作交给 ProjectRow。
export function ProjectList(props: ProjectListProps): ReactElement {
  const { loadState, projects, keyword, status, busyProjectId, onKeywordChange, onStatusChange, onClearFilters, onRetry, onStatusChangeForProject, onRenameProject, onArchiveProject, onOpenPath, onDevelop, onImportTemplate, onCreateProject } = props; const hasFilter = keyword.trim() !== '' || status !== 'all';
  return <><div className="filter-bar"><Input.Search value={keyword} onChange={(event) => onKeywordChange(event.target.value)} placeholder="搜索项目名称" allowClear /><Select value={status} onChange={onStatusChange} options={(Object.keys(PROJECT_FILTER_LABELS) as ProjectStatusFilter[]).map((key) => ({ value: key, label: PROJECT_FILTER_LABELS[key] }))} /><Button type="link" onClick={onClearFilters} disabled={!hasFilter}>清空筛选</Button></div>{loadState === 'loading' && <div className="loading-line"><Spin /> 正在加载项目</div>}{loadState === 'error' && <div className="error-panel"><Typography.Text strong>项目列表加载失败</Typography.Text><Typography.Text type="secondary">无法读取本地数据库，请稍后重试。</Typography.Text><Button onClick={onRetry}>重新加载</Button></div>}{loadState === 'ready' && projects.length === 0 && <Empty description={hasFilter ? '没有找到匹配的项目' : '还没有毕业项目'}><Button onClick={hasFilter ? onClearFilters : onImportTemplate}>{hasFilter ? '清空筛选' : '导入代码模板'}</Button>{!hasFilter && <Button type="link" onClick={onCreateProject}>新建项目</Button>}</Empty>}{loadState === 'ready' && projects.length > 0 && <><Typography.Text type="secondary">共 {projects.length} 个项目</Typography.Text><ul className="project-table">{projects.map((project) => <ProjectRow key={project.id} project={project} busy={busyProjectId === project.id} onStatusChange={onStatusChangeForProject} onRename={onRenameProject} onArchive={onArchiveProject} onOpenPath={onOpenPath} onDevelop={onDevelop} />)}</ul></>}</>;
}
